name: Basics CICD pipeline - Github Hosted Runner
on:
  push
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: mvn clean
  compile:
    runs-on: ubuntu-latest
    needs: clean
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: mvn compile
  staticanalysis:
    needs: compile
    uses: arslakin/maven-register-app2/.github/workflows/sonarcloud-analysis1.yml@main
    with:
      projectKey: "arslakin_maven-register-app2"
      organization: "arslakin"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  unittesting:
    runs-on: ubuntu-latest
    needs: staticanalysis
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: unittesting
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: mvn package








          


    
