name: Static Analysis using Sonar Cloud
on: 
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
    inputs:
      projectKey:
        required: true
        type: string
      organization:
        required: true
        type: string
  
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: |
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=arslakin \
        -Dsonar.projectKey=arslakin_maven-register-app2
